### ISSUE TITLE
Intel Card: Error setting video mode: Couldn't find matching GLX visual.

### ISSUE THREAD

**Issue by md-5** [emezeske/digbuild#25]
src/sdl_gl_window.cc +117 prepare_resolution(): Chosen resolution: (1920, 1080)
src/main.cc +33 main(): Error: Error setting video mode: Couldn't find matching GLX visual.

I'm on Ubuntu 12.04 64bit.
The define=EVAN workaround did not change anything.

I must point out that this is only an issue when running with my Intel SandyBridge mobile graphics chipset and not when using my Nvidia 525m card.

Digbuild looks nice :)

**Comment by blak3mill3r** [comment]
Grep the source code for EVAN, or for 1920, find his define, change the
constants to a resolution your gfx card supports.

HTH

On Mon, Jun 18, 2012 at 4:30 AM, md-5 <
reply@reply.github.com

**Comment by md-5** [comment]
Yeah I already looked at the EVAN stuff, would have maybe my intel just doesn't support 3d at that res. Since it is a dual card system I am using the intel one now.

**Comment by blak3mill3r** [comment]
If you haven't tried 640x480 yet, I suggest doing that. If that doesn't
work, your card might not support the requested visual at all (at any
resolution).

The lines below (from sdl_gl_window.cc) may need to be changed if that's
the case.
It's requesting a double buffered visual at 24-bits-per-pixel, check if
your card supports that (run glxinfo)

If you find that your card doesn't support the visual you can try lowering
some of those values in SDL_GL_SetAttribute.

It is also quite possible that digbuild just will not run on this card. It
definitely won't work without a depth buffer, beyond that I'm not sure what
the minimum requirements are.

After trying 640x480 I would try commenting out the multisampling stuff
first.

Good luck!

```
SDL_GL_SetAttribute( SDL_GL_RED_SIZE, 8 );
SDL_GL_SetAttribute( SDL_GL_GREEN_SIZE, 8 );
SDL_GL_SetAttribute( SDL_GL_BLUE_SIZE, 8 );
SDL_GL_SetAttribute( SDL_GL_ALPHA_SIZE, 8 );
SDL_GL_SetAttribute( SDL_GL_DEPTH_SIZE, 24 );
SDL_GL_SetAttribute( SDL_GL_DOUBLEBUFFER, 1 );

// TODO: Antialiasing level should be configurable.
SDL_GL_SetAttribute( SDL_GL_MULTISAMPLEBUFFERS, 1 );
SDL_GL_SetAttribute( SDL_GL_MULTISAMPLESAMPLES, 4 );

// TODO: Vsync should be configurable.
SDL_GL_SetAttribute( SDL_GL_SWAP_CONTROL, 1 );

// FIXME: Don't hack the resolution here; make this work with multiple
```

monitors.
#if defined BLAKE
    resolution_ = Vector2i( 1920, 1200 );
#elif defined EVAN
    resolution_ = Vector2i( 1024, 768 );
#endif

http://comments.gmane.org/gmane.comp.lib.sdl/12498

On Mon, Jun 18, 2012 at 2:29 PM, md-5 <
reply@reply.github.com
